apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-api-proxy
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: proxy
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
spec:
  resources:
    requests:
      storage: 500Mi
