apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
stringData:
  username: production_proxy
  password: replace-with-production-password
---
apiVersion: v1
kind: Secret
metadata:
  name: github-api-credentials
stringData:
  token: replace-with-production-github-token
