apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-deployment.yaml
  - app-service.yaml
  - github-api-credentials-secret.yaml
  - ingress.yaml
  - mongodb-community.yaml
  - mongodb-appdb-rbac.yaml
  - database-credentials-secret.yaml
  - rotator-rbac.yaml
  - rotator-cronjob.yaml

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=production
      - CACHE_TTL_SECONDS=300
      - MONGO_DATABASE=github_proxy

labels:
  - pairs:
      app.kubernetes.io/name: github-api-proxy
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
