apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-deployment.yaml
  - app-service.yaml
  - database-credentials-secret.yaml
  - github-api-credentials-secret.yaml
  - ingress.yaml
  - mongodb-deployment.yaml
  - mongodb-pvc.yaml
  - mongodb-service.yaml
  - mongodb-network-policy.yaml

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=production
      - CACHE_TTL_SECONDS=300

labels:
  - pairs:
      app.kubernetes.io/name: github-api-proxy
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
