apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "8.0.4"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: github-proxy
      db: admin
      passwordSecretRef:
        name: database-credentials
        key: password
      roles:
        - name: readWrite
          db: github_proxy
      scramCredentialsSecretName: database-credentials-scram
      connectionStringSecretName: database-credentials-connection
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
