apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-api-proxy-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: github-api-proxy
    newName: github-api-proxy
    newTag: dev

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - CACHE_TTL_SECONDS=60

patches:
  - path: environment-patch.yaml
  - path: secrets-patch.yaml
  - path: capacity-patch.yaml
  - path: service-patch.yaml
  - path: ingress-delete-patch.yaml
