apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-api-proxy-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: github-api-proxy
    newName: github-api-proxy
    newTag: dev

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - CACHE_TTL_SECONDS=60
      - MONGO_DATABASE=github_proxy_dev

patches:
  - path: environment-patch.yaml
  - path: secrets-patch.yaml
  - path: capacity-patch.yaml
  - path: service-patch.yaml
  - path: ingress-delete-patch.yaml
  - target:
      group: mongodbcommunity.mongodb.com
      version: v1
      kind: MongoDBCommunity
      name: mongodb
    patch: |-
      - op: replace
        path: /spec/users/0/roles/0/db
        value: github_proxy_dev
