apiVersion: v1
kind: Secret
metadata:
  name: rotator-mongodb-credentials
stringData:
  password: replace-with-dev-mongo-root-password
---
apiVersion: v1
kind: Secret
metadata:
  name: github-api-credentials
stringData:
  token: replace-with-dev-github-token
