apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
stringData:
  username: dev_proxy
  password: replace-with-dev-password
---
apiVersion: v1
kind: Secret
metadata:
  name: github-api-credentials
stringData:
  token: replace-with-dev-github-token
