apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-api-proxy
spec:
  replicas: 2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
spec:
  resources:
    requests:
      storage: 200Mi
