apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-api-proxy
spec:
  template:
    spec:
      containers:
        - name: proxy
          env:
            - name: MONGO_DATABASE
              value: github_proxy_staging
