apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
stringData:
  username: staging_proxy
  password: replace-with-staging-password
---
apiVersion: v1
kind: Secret
metadata:
  name: github-api-credentials
stringData:
  token: replace-with-staging-github-token
