apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
stringData:
  password: replace-with-staging-mongo-app-password
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-root-credentials
stringData:
  username: replace-with-staging-mongo-root-username
  password: replace-with-staging-mongo-root-password
---
apiVersion: v1
kind: Secret
metadata:
  name: github-api-credentials
stringData:
  token: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-keyfile
stringData:
  key: replaceWithStgMongoKey
